language: java
jdk: openjdk8
notifications:
  slack:
    secure: I5IBa62VSxr+D7GHcTgoR6s8xG5PPXHIDAy2zsRhqp+XI4QVCJ3LkzYVqoUHtcaxF8y9Z6ndY7zK0ejG/QjCjfm9EphNNP9eHGE7MbYJYqDZiNMwUhbFUfO8yGIx0rpr7DRcp2F6C7H8AsCpPminxQArcyXJAoKdfbOlo7G3BZXcpX8CRmSyUbs9N6nHrJymZiF7DCkPsU7XNMGE+38kh0tewVceCQczI1Jg+Qkz2OHedEXnuZN4egdNgCi2o83j1R7XGql/AWijQh+aNoROwNeKDFntZIcFvpUnLNvRqlT7rbzNG0xM1MlpcUt2txPbrFrq74FODaIGjbLgom0HhWNVM7L5BoubyLx79vBLMhG7ZosAbWanXw/VyrjLRErcVnbr1duf1eNbaVYaScN3h+PXg/fKidyxMkrhFvP1ItX8dAuV+sCIa9BtbctMVoukavmtS+8K7NAgjphOfPbj7DybW261yxeUf179cLdg7lKIY5u8r9C7Ri5s3cWCg5YAiVhEMZPl10B8SuvtFCaB1AmnljIlV5xmTHaI/EksrO+LYXUmuIYkQWlkl3MEFHdOnsF7ef9ZSO+tY1jFSdFnfbF1dBF67cm2N8YptR6OCNwMFCiBun4bQ97nNP4NlcexlVyaFci2bEWzwxHmpcRTIAgmJSQDyMWLnCTpWN4+AUI=
deploy:
  provider: releases
  api_key:
    secure: i7ITo3naP4gENjX5suen0FqJ3PRsr8rhVjA/JxZfCGwz2aTGgAOKKQahjN8lrSxlRCs/2/DGpFW3COX40GvNWxqGB13LH9BFoEsnzEX21FD9RKm/O8unX4q4KQkyGOxk5lGFPID2JOssUtJfkuEiTfZjfFOe9BL6SypX5dQb9+cd4lVstS1zRIQYTN8SI4tzsClAg5ZEGymm4KFvOcwCKaBxUmhOAO9AhE+gGXoUQ6CoCgWgNWZb/0XXutCDmfe8Pd8lQqUXUFYvSkjfGOXU/eQysJa6wffGfgX9zustXwiBMr4vFa0OwvA+0VQApYJuCcJgmCFajA43/l50/L842c6/YuRd8rYhrH7A13Aj1rOgfHA4Kpj9PHYajO6Fbq2nFX9kiM6DJcR9rRhy7knHY+lWcRGLpT8jXFx0fkjLw2/1bt9VXUdfhAza+BQySe0SEVG5eeqkAXYB4IJchH4uZt8KX8a17Vem+L6jsEShjIaOK7PsA+xJWp4wDAIS463ijEeBWOHnh/d/YlbYW7N9gkVa6Tfg5fbTKt8wD1tB4tRwtfRbKACUY3kUs93ClGgMvPbmMd64elmW7PsTlb8h3ELmLop2AtcH3jKtYuCposw/8e+AmF3Qj+cOpPCpM5Daf5c/9T9BY21fkLihoL667lbnP9s1lGXntMkJLsU7gWs=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-ispw-plugin